version: '3.7'

services:
  # Build the app services
  app:
    build: app
    restart: always
    # replace <LOCATION_ON_DRIVE> with the absolute path to the folder below
    volumes:
      - <LOCATION_ON_DRIVE>\field_study_logo2brand:/field_study_logo2brand
      - <LOCATION_ON_DRIVE>\data:/data

  nginx:
    build: loadbalancer
    restart: always
    # Bind the port 80 of container to machine port 80
    ports:
      - 8010:80
    # Make app as nginx dependency service
    depends_on:
      - app
